# Generated by Django 5.2.4 on 2025-07-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Informasi Batch',
                'verbose_name_plural': 'Informasi Batch',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Produk')),
                ('theoritical_yield_pcs', models.PositiveIntegerField(help_text='Jumlah unit produk yang seharusnya dihasilkan secara teori.', verbose_name='Theoretical Yield (pcs)')),
                ('target_yield_percent', models.FloatField(help_text='Target persentase yield yang diharapkan untuk produk ini.', verbose_name='Target Yield (%)')),
            ],
            options={
                'verbose_name': 'Master Produk',
                'verbose_name_plural': 'Master Produk',
            },
        ),
        migrations.CreateModel(
            name='MSTDTargetNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yieldapp.batchinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorYieldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_proses', models.DateField(help_text='Tanggal dimulainya proses batch ini')),
                ('filling_output', models.PositiveIntegerField(blank=True, null=True)),
                ('inspection_output', models.PositiveIntegerField(blank=True, null=True)),
                ('assembly_output', models.PositiveIntegerField(blank=True, null=True)),
                ('blistering_output', models.PositiveIntegerField(blank=True, null=True)),
                ('packaging_output', models.PositiveIntegerField(blank=True, null=True)),
                ('handover_output', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yieldapp.batchinfo')),
            ],
            options={
                'verbose_name': 'Operator Yield Data',
                'verbose_name_plural': 'Operator Yield Data',
                'ordering': ['-tanggal_proses', 'batch'],
            },
        ),
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(choices=[('filling', 'Filling'), ('inspection', 'Inspection'), ('assembly', 'Assembly'), ('blistering', 'Blistering'), ('packaging', 'Packaging'), ('handover', 'Handover')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_target', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yieldapp.batchinfo')),
            ],
        ),
        migrations.AddField(
            model_name='batchinfo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='yieldapp.product'),
        ),
    ]
