# Generated by Django 5.2.4 on 2025-07-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yieldapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processdata',
            name='batch',
        ),
        migrations.DeleteModel(
            name='MSTDTargetNote',
        ),
        migrations.DeleteModel(
            name='ProcessData',
        ),
    ]
