# Generated by Django 5.2.4 on 2025-07-21 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldapp', '0002_remove_processdata_batch_delete_mstdtargetnote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatoryielddata',
            options={'ordering': ['-tanggal_proses', 'batch'], 'verbose_name': 'Data Yield Operator', 'verbose_name_plural': 'Data Yield Operator'},
        ),
        migrations.AddField(
            model_name='operatoryielddata',
            name='formulation_output_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Output Formulasi (Kg)'),
        ),
        migrations.AddField(
            model_name='operatoryielddata',
            name='formulation_output_pcs',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Output Formulasi (setara Pcs)'),
        ),
        migrations.AlterField(
            model_name='operatoryielddata',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_data', to='yieldapp.batchinfo'),
        ),
        migrations.AlterField(
            model_name='operatoryielddata',
            name='handover_output',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Handover to Warehouse (pcs)'),
        ),
    ]
