# Generated by Django 5.2.4 on 2025-07-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldapp', '0003_alter_operatoryielddata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfo',
            name='status',
            field=models.CharField(choices=[('Formulation', 'Formulasi'), ('Filling', 'Filling'), ('Inspection', 'Inspeksi'), ('Assembly', 'Assembly'), ('Blistering', 'Blistering'), ('Packaging', 'Packaging'), ('Handover', 'Handover'), ('Completed', 'Selesai')], default='Formulation', max_length=50, verbose_name='Status Proses'),
        ),
    ]
